# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e908125cf6ac2121cb10d3f2f36300571c080ef809de62b24cf46bc877ff84e02ddc791c29d004f9c12fc4e92d061128977110e0b8ab8adaa13d9aacf576b5fe

test:
  secret_key_base: 77c82c9d67243eeec74967e6e6b8f4407ebf785d1278ecc23b00a79bd795c2ab028aa133bb9a1bfc75ce93c7b08961c01fbf67e64eb53ffc85e085193a2c52a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
